package openvr.steamVR_Input.actionSetClasses

import openvr.steamVR.input.*
import openvr.steamVR_Input.SteamVR_Actions

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class SteamVR_Input_ActionSet_default : SteamVR_ActionSet() {

    val interactUI: SteamVR_Action_Boolean
        get() = SteamVR_Actions.default_InteractUI

    val teleport: SteamVR_Action_Boolean
        get() = SteamVR_Actions.default_Teleport

    val grabPinch: SteamVR_Action_Boolean
        get() = SteamVR_Actions.default_GrabPinch

    val grabGrip: SteamVR_Action_Boolean
        get() = SteamVR_Actions.default_GrabGrip

    val pose: SteamVR_Action_Pose
        get() = SteamVR_Actions.default_Pose

    val skeletonLeftHand: SteamVR_Action_Skeleton
        get() = SteamVR_Actions.default_SkeletonLeftHand

    val skeletonRightHand: SteamVR_Action_Skeleton
        get() = SteamVR_Actions.default_SkeletonRightHand

    val squeeze: SteamVR_Action_Single
        get() = SteamVR_Actions.default_Squeeze

    val headsetOnHead: SteamVR_Action_Boolean
        get() = SteamVR_Actions.default_HeadsetOnHead

    val haptic: SteamVR_Action_Vibration
        get() = SteamVR_Actions.default_Haptic
}