package openvr.steamVR_Input.actionSetClasses

import openvr.assets.steamVR.input.SteamVR_ActionSet
import openvr.assets.steamVR.input.SteamVR_Action_Pose
import openvr.steamVR_Input.SteamVR_Actions

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

class SteamVR_Input_ActionSet_mixedreality : SteamVR_ActionSet() {

    val externalCamera:  SteamVR_Action_Pose
        get() = SteamVR_Actions.mixedreality_ExternalCamera
}
